export {default as DashboardStack} from "./DashboardStack"
export {default as AuthStack} from "./AuthStack"
export {default as Tabs} from "./Tabs"
export {default as service} from "./service"
export {default as MainNavigator} from "./MainNavigator"
